numbers_words = [
    "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten",
    "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", 
    "Eighteen", "Nineteen", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", 
    "Eighty", "Ninety", "One hundred", "One thousand", "Ten thousand", "One million", 
    "One billion"
]

numbers = [
    'Один',
    'Два',
    'Три',
    'Четыре',
    'Пять',
    'Шесть',
    'Семь',
    'Восемь',
    'Девять',
    'Десять',
    'Одиннадцать',
    'Двенадцать',
    'Тринадцать',
    'Четырнадцать',
    'Пятнадцать',
    'Шестнадцать',
    'Семнадцать',
    'Восемнадцать',
    'Девятнадцать',
    'Двадцать',
    'Тридцать',
    'Сорок',
    'Пятьдесят',
    'Шестьдесят',
    'Семьдесят',
    'Восемьдесят',
    'Девяносто',
    'Сто',
    'Тысяча',
    'Десять тысяч',
    'Миллион',
    'Миллиард',
]

numbers_translation = {
    "One": "Один",
    "Two": "Два",
    "Three": "Три",
    "Four": "Четыре",
    "Five": "Пять",
    "Six": "Шесть",
    "Seven": "Семь",
    "Eight": "Восемь",
    "Nine": "Девять",
    "Ten": "Десять",
    "Eleven": "Одиннадцать",
    "Twelve": "Двенадцать",
    "Thirteen": "Тринадцать",
    "Fourteen": "Четырнадцать",
    "Fifteen": "Пятнадцать",
    "Sixteen": "Шестнадцать",
    "Seventeen": "Семнадцать",
    "Eighteen": "Восемнадцать",
    "Nineteen": "Девятнадцать",
    "Twenty": "Двадцать",
    "Thirty": "Тридцать",
    "Forty": "Сорок",
    "Fifty": "Пятьдесят",
    "Sixty": "Шестьдесят",
    "Seventy": "Семьдесят",
    "Eighty": "Восемьдесят",
    "Ninety": "Девяносто",
    "One hundred": "Сто",
    "One thousand": "Тысяча",
    "Ten thousand": "Десять тысяч",
    "One million": "Миллион",
    "One billion": "Миллиард"
}

farewells = [
    'Goodbye.',
    'Bye.',
    'See you later.',
    'Take care.',
    'Have a nice day.',
    'See you soon.',
    'Catch you later.',
    'Farewell.',
    'Take it easy.',
    'See you tomorrow.',
    'Good night.',
    'See you next time.',
    'Until next time.',
    'I\'m off.',
    'Catch you later.',
    'I\'m heading out.',
    'Have a good one.',
    'All the best.',
    'Take care of yourself.',
    'So long.',
    'Until we meet again.',
    'See you around.',
    'Godspeed.',
    'Bye for now.',
    'Keep in touch.',
    'Have a great day.',
    'See you in a bit.',
    'Peace out.',
    'Later.',
    'Take it easy.'
]

weeks = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']